name: 'Flake8 Pull Request Commenter'
description: 'Comment PR lines with Flake8 detected errors'
inputs:
  cfg_path:
    description: 'Path of the configuration file for Flake8'
    required: false
    default: ''
  github_token:
    description: 'This is an authorization token that grants pull request write access to make it possible to write review comments in the PR.'
    required: true
  plugins:
    description: 'List of Flake8 plugins to be installed before analyzing the code'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: "Install Flake8 dependencies"
      run: python -m pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash
    - name: "Install Flake8 plugins"
      run: python -m pip install ${{ inputs.plugins }}
      shell: bash
    - name: "Run Flake8 and send comments to comment"
      env:
        FLAKE8_CFG_PATH: ${{ inputs.cfg_path }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GITHUB_PULL_NUMBER: ${{github.event.pull_request.number}}
        GITHUB_COMMIT: ${{ github.event.pull_request.head.sha }}
        GITHUB_OWNER: ${{ github.event.pull_request.head.repo.owner.login }}
        GITHUB_REPO: ${{ github.event.repository.name }}
      run: python ${{ github.action_path }}/src/main.py
      shell: bash